// Generated by CoffeeScript 1.3.3
(function() {
  var Bar, Geometry,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Geometry = (function() {

    function Geometry(geom, mesh, pos) {
      this.geometry = new THREE.Mesh(geom, mesh);
      this.setPosition(pos);
    }

    Geometry.prototype.getGeometry = function() {
      return this.geometry;
    };

    Geometry.prototype.setPosition = function(pos) {
      return this.geometry.position.set(pos.x, pos.y, pos.z);
    };

    return Geometry;

  })();

  Bar = (function(_super) {

    __extends(Bar, _super);

    function Bar(x_width, height, z_width, pos, color) {
      var geom, mesh;
      this.x_width = x_width;
      this.height = height;
      this.z_width = z_width;
      geom = new THREE.CubeGeometry(x_width, height, z_width);
      mesh = new THREE.MeshLambertMaterial({
        color: color
      });
      this.centroid = this.calCentroid(pos);
      Bar.__super__.constructor.call(this, geom, mesh, this.centroid);
    }

    Bar.prototype.calCentroid = function(pos) {
      pos.y += this.height / 2;
      return pos;
    };

    return Bar;

  })(Geometry);

  this.Bar = Bar;

}).call(this);
