// Generated by CoffeeScript 1.3.3
(function() {
  var Vizz;

  Vizz = {
    version: 0.02,
    author: 'ZERO',
    description: 'Vizz is a little library of data visualization in 3D.'
  };

  this.Vizz = Vizz;

}).call(this);
