// Generated by CoffeeScript 1.3.3
(function() {

  this.Vizz || (this.Vizz = {
    version: 0.02,
    author: 'ZERO',
    description: 'Vizz is a little library of data visualization in 3D.',
    Core: {
      description: 'Core data structures.'
    },
    EventHandler: {
      description: 'Mouse event handler and keyboard event handler.'
    },
    Utils: {
      description: 'Useful helper methods.'
    },
    Primitive: {
      description: 'Different kinds of graphical primitives.'
    },
    Graphics: {
      description: 'Different forms of graphics.'
    }
  });

}).call(this);
