// Generated by CoffeeScript 1.3.3
(function() {

  this.Vizz.Core.Coordinate = {
    cartesian: function(x, z) {
      return {
        x: x,
        y: 0,
        z: z
      };
    },
    polar: function(theta, r) {
      return {
        x: r * Math.cos(theta),
        y: 0,
        z: r * Math.sin(theta)
      };
    },
    getCoordinate: function(type) {
      switch (type) {
        case 'CARTESIAN':
          return this.cartesian;
        case 'POLAR':
          return this.polar;
        default:
          return this.cartesian;
      }
    }
  };

}).call(this);
