// Generated by CoffeeScript 1.3.3
(function() {
  var Curve;

  Curve = (function() {

    function Curve(func, range, accuracy) {
      this.func = func;
      this.range = range;
      this.accuracy = accuracy;
    }

    Curve.prototype.length = function() {
      var len, x;
      len = 0;
      x = this.range.begin;
      while (x < this.range.end) {
        len += Auxiliary.dist2(0, this.func(x), this.accuracy, this.func(x + this.accuracy));
        x += this.accuracy;
      }
      return len;
    };

    Curve.prototype.stops = function(n) {
      var counter, len, step, stops, x;
      len = 0;
      counter = 0;
      x = this.range.begin;
      step = this.length() / n;
      stops = [];
      while (counter < n) {
        if (len >= step) {
          len = 0;
          stops.push({
            x: x,
            z: this.func(x)
          });
          counter++;
        }
        len += Auxiliary.dist2(0, this.func(x), this.accuracy, this.func(x + this.accuracy));
        x += this.accuracy;
      }
      return stops;
    };

    return Curve;

  })();

  this.Curve = Curve;

}).call(this);
