// Generated by CoffeeScript 1.3.3
(function() {
  var Coordinate, Curve, Distance;

  Distance = Vizz.Core.Distance;

  Coordinate = Vizz.Core.Coordinate;

  Curve = (function() {

    function Curve(func, type, range, accuracy) {
      this.func = func;
      this.type = type;
      this.range = range;
      this.accuracy = accuracy;
      this.distance = Distance.getDistance(this.type);
      this.coordinate = Coordinate.getCoordinate(this.type);
    }

    Curve.prototype.length = function() {
      var len, x;
      len = 0;
      x = this.range.begin;
      while (x < this.range.end) {
        len += this.distance(0, this.func(x), this.accuracy, this.func(x + this.accuracy));
        x += this.accuracy;
      }
      return len;
    };

    Curve.prototype.stops = function(n) {
      var counter, len, step, stops, x;
      len = 0;
      counter = 0;
      x = this.range.begin;
      step = this.length() / n;
      stops = [];
      while (counter < n) {
        if (len >= step) {
          len = 0;
          stops.push(this.coordinate(x, this.func(x)));
          counter++;
        }
        len += this.distance(0, this.func(x), this.accuracy, this.func(x + this.accuracy));
        x += this.accuracy;
      }
      return stops;
    };

    return Curve;

  })();

  this.Vizz.Core.Curve = Curve;

}).call(this);
