// Generated by CoffeeScript 1.3.3
(function() {

  this.Vizz.Core.Distance = {
    segment: function(x, y) {
      return Math.sqrt(x * x + y * y);
    },
    cartesian: function(x1, y1, x2, y2) {
      return Math.sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1));
    },
    polar: function(theta1, r1, theta2, r2) {
      return Math.sqrt(r1 * r1 + r2 * r2 - 2 * r1 * r2 * Math.cos(theta2 - theta1));
    },
    getDistance: function(type) {
      switch (type) {
        case 'CARTESIAN':
          return this.cartesian;
        case 'POLAR':
          return this.polar;
        default:
          return this.cartesian;
      }
    }
  };

}).call(this);
