// Generated by CoffeeScript 1.3.3
(function() {
  var Range, Rect;

  Range = (function() {

    function Range(begin, end) {
      if (begin <= end) {
        this.begin = begin;
        this.end = end;
      } else {
        this.begin = end;
        this.end = begin;
      }
    }

    Range.prototype.length = function() {
      return this.end - this.begin;
    };

    Range.prototype.contain = function(i) {
      return (this.begin <= i && i <= this.end);
    };

    Range.prototype.center = function() {
      return (this.begin + this.end) / 2;
    };

    Range.prototype.half = function() {
      return this.end - this.center();
    };

    return Range;

  })();

  Rect = (function() {

    function Rect(range1, range2) {
      this.x = range1;
      this.z = range2;
    }

    Rect.prototype.contain = function(p) {
      return this.x.contain(p.x) && this.z.contain(p.z);
    };

    Rect.prototype.center = function() {
      return {
        x: (range1.begin + range2.begin) / 2,
        z: (range1.end + range2.end) / 2
      };
    };

    Rect.prototype.half = function() {
      return {
        x: this.x.end - this.center.x,
        z: this.z.end - this.center.z
      };
    };

    return Rect;

  })();

  this.Vizz.Core.Range = Range;

  this.Vizz.Core.Rect = Rect;

}).call(this);
