// Generated by CoffeeScript 1.3.3
(function() {
  var Coordinate;

  Coordinate = {
    cartesian: function(x, z) {
      return {
        x: x,
        z: z
      };
    },
    polar: function(theta, r) {
      return {
        x: r * Math.cos(theta),
        z: r * Math.sin(theta)
      };
    },
    getCoordinate: function(type) {
      switch (type) {
        case 'CARTESIAN':
          return this.cartesian;
        case 'POLAR':
          return this.polar;
        default:
          return this.cartesian;
      }
    }
  };

  this.Coordinate = Coordinate;

}).call(this);
