// Generated by CoffeeScript 1.3.3
(function() {
  var Generator;

  Generator = {
    randomGrid: function(x_range, z_range, vibration) {
      var grid, x, z;
      grid = (function() {
        var _i, _results;
        _results = [];
        for (x = _i = 0; 0 <= x_range ? _i < x_range : _i > x_range; x = 0 <= x_range ? ++_i : --_i) {
          _results.push((function() {
            var _j, _results1;
            _results1 = [];
            for (z = _j = 0; 0 <= z_range ? _j < z_range : _j > z_range; z = 0 <= z_range ? ++_j : --_j) {
              _results1.push(Vizz.Random.range(0, vibration));
            }
            return _results1;
          })());
        }
        return _results;
      })();
      return grid;
    }
  };

  this.Generator = Generator;

}).call(this);
