// Generated by CoffeeScript 1.3.3
(function() {
  var Random;

  Random = {
    range: function(begin, end) {
      return begin + (end - begin) * Math.random();
    }
  };

  this.Random = Random;

}).call(this);
