// Generated by CoffeeScript 1.3.3
(function() {
  var Range;

  Range = (function() {

    function Range(begin, end) {
      if (begin <= end) {
        this.begin = begin;
        this.end = end;
      } else {
        this.begin = end;
        this.end = begin;
      }
    }

    Range.prototype.length = function() {
      return this.end - this.begin;
    };

    Range.prototype.contain = function(i) {
      return (this.begin <= i && i <= this.end);
    };

    return Range;

  })();

  this.Range = Range;

}).call(this);
