// Generated by CoffeeScript 1.3.3
(function() {
  var Bar, Histogram, Scaler;

  Scaler = this.Vizz.Core.Scaler;

  Bar = this.Vizz.Primitive.Bar;

  Histogram = (function() {

    function Histogram(raw_data, renderer) {
      this.raw_data = raw_data;
      this.renderer = renderer;
    }

    Histogram.prototype.process = function(curve, range) {
      var i, stops;
      stops = curve.stops(this.raw_data.length);
      curve.scale(stops, range);
      return this.render_data = (function() {
        var _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = this.raw_data.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          _results.push({
            pos: stops[i],
            val: this.raw_data[i]
          });
        }
        return _results;
      }).call(this);
    };

    Histogram.prototype.render = function() {
      var i, _i, _ref, _results;
      _results = [];
      for (i = _i = 0, _ref = this.render_data.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        _results.push(this.renderer.add(new Bar(this.render_data[i].val, this.render_data[i].pos)));
      }
      return _results;
    };

    Histogram.prototype.onCurve = function(curve, range) {
      this.process(curve, range);
      return this.render();
    };

    return Histogram;

  })();

  this.Vizz.Graphics.Histogram = Histogram;

}).call(this);
