// Generated by CoffeeScript 1.3.3
(function() {
  var Bar, Geometry,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Geometry = this.Vizz.Primitive.Geometry;

  Bar = (function(_super) {

    __extends(Bar, _super);

    Bar.prototype.CONFIG = {
      color: 0x0000ff,
      opacity: 0.5,
      radius: 5
    };

    function Bar(height, pos, config) {
      var geom, mesh;
      this.height = height;
      this.setConfig(config, this.CONFIG);
      geom = new THREE.CubeGeometry(this.CONFIG.radius, height, this.CONFIG.radius);
      mesh = new THREE.MeshLambertMaterial({
        color: this.CONFIG.color,
        opacity: this.CONFIG.opacity,
        transparent: true
      });
      this.calCentroid(pos);
      Bar.__super__.constructor.call(this, geom, mesh, pos);
    }

    Bar.prototype.calCentroid = function(pos) {
      return pos.y += this.height / 2;
    };

    Bar.prototype.onFocus = function() {
      return this.geometry.material.opacity = 1;
    };

    Bar.prototype.loseFocus = function() {
      return this.geometry.material.opacity = this.CONFIG.opacity;
    };

    return Bar;

  })(Geometry);

  this.Vizz.Primitive.Bar = Bar;

}).call(this);
