// Generated by CoffeeScript 1.3.3
(function() {
  var Geometry;

  Geometry = (function() {

    function Geometry(geom, mesh, pos) {
      this.geometry = new THREE.Mesh(geom, mesh);
      this.setPosition(pos);
    }

    Geometry.prototype.getGeometry = function() {
      return this.geometry;
    };

    Geometry.prototype.setPosition = function(pos) {
      return this.geometry.position.set(pos.x, pos.y, pos.z);
    };

    return Geometry;

  })();

  this.Vizz.Primitive.Geometry = Geometry;

}).call(this);
